services:
  - type: web
    name: ramigame
    runtime: docker
    rootDir: app
    plan: free
    envVars:
      - key: SITE_URL
        value: https://ramigame.onrender.com
      - key: SESSION_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
